### PR TITLE
TASK: Adjust to Flow 7 logger injection change

### LINKED ISSUE #30: Release Flow 6.x and 7.x compatible versions?
Will there be releases that are marked compatible with Flow 6.x and/or 7.x? (right now, composer.json denies installation in any installation newer than Flow 5.x)

- [x] #29 
- [ ] #31

### PR DESCRIPTION
**Pull request by albe**
See https://github.com/neos/flow-development-collection/pull/2134

Resolves #30

### CODE REVIEW

**Comment by albe** [comment]
@mrimann would be great if you had feedback on this branch on a 7.0 installation

**Comment by kdambekalns** [comment]
@mrimann Any feedback you can share?

**Comment by mrimann** [comment]
@kdambekalns sorry, not yet - we postponed the upgrade of our application since there was another dependency of a package that was not yet compatible with Flow 7.x (and since then, I didn't have a second look at upgrading that application at all as other things were more urgent, sorry).

**Comment by albe** [comment]
Given this surely doesn't break something as only the injection annotation changes and Flow 7 is required, how about we merge this and tag a new major release of the package? @kdambekalns In case some things are still not quite perfect 🤞 with Flow 7 we can fix this with a follow-up but at least the package is installable with seven so we can get feedback?

**Review by kdambekalns — APPROVED** [review]

**Pull request merged**
