### PR TITLE
TASK: Add Flow 6.x compatibility

### PR DESCRIPTION
**Pull request by gerdemann**

### CODE REVIEW

**Review by kdambekalns — COMMENTED** [review]
Fine with me, but doesn't the removed logging make debugging login issues a lot harder? Why not log to the `PsrLoggerInterface` instead? To keep it compatible with 4/5/6 at the same time?

**Comment by DrillSergeant** [comment]
We need this package for the current Flow LTS (6.3), too. @gerdemann do you have plans to finish this PR? Or shall we take over the part about logging?

**Comment by gerdemann** [comment]
Unfortunately I do not have time for this at the moment. You are welcome to do the logging part.

**Comment by DrillSergeant** [comment]
Ok, we will take over that fork (into our repository) and open it again as new PR

**Pull request closed without merging**
